import { SectionListRenderItemInfo } from "react-native";

export interface token {
    token:string;
}

export interface userToken {
    email: string;
    token: token[];
}

export interface NotTypeCard {
    idUser: string,
    idFilterType: string,
    filterName: string,
    notificationsNumber: string,
}

// Generated by https://quicktype.io

export interface Notification {
    id:                 number;
    idAprobacion:       number;
    idEmpleado:         number;
    idSolicitante:      number;
    solicitante:        string;
    tipoProceso:        number;
    etapaProceso:       number;
    agencia:            null;
    departamento:       string;
    identificador:      string;
    not_identificador:  string;
    fecha:              string;
    descripcionCorta:   string;
    descripcionLarga:   string;
    link:               string;
    adjunto:            null;
    tipoAdjunto:        null;
    modalidadAdjunto:   number;
    tipoNotificacion:   number;
    chat:               number;
    chatPendiente:      number;
    agrupacion:         number;
    correoEnviado:      number;
    escalado:           number;
    nivel:              number;
    estatus:            number;
    estado:             number;
    idEmpresa:          null;
    idSucursal:         null;
    idDepartamento:     null;
    MinutosFaltan:      number;
    comentarioRevision: null | string;
    ruta_archivos:      string;
    Depto:              null;
    esPlanta:           number;
    estatusLote:        null;
    diasNot:            number;
    existeNotNueva:     number;
}
